# Module 3: MLR: Statistical Modeling vs Machine Learning

> ```
> -In this notebook, you will explore how you can estimate the MLR following a Statistical Modeling and Machine Learning style.
> -Why does this matter?
>     1. MLR will be your first model in many ML projects, and you should know which approach is the most suitable.
>     2. Getting comfortable with this learning algorithm will help you understand more complex ones.
> ```

## 1. Import packages

 **Most widely used packages for Statistical Modeling and Machine Learning:**
* statsmodels → OLS, statistical modeling style (inference, p-values, CIs).
* scikit-learn → LinearRegression (OLS under the hood) and SGDRegressor (gradient descent optimization).


In [1]:
import numpy as np
import time
from sklearn.linear_model import LinearRegression, SGDRegressor
import statsmodels.api as sm
from sklearn.preprocessing import StandardScaler

## 2. Make toy data

In [2]:
### 1-Create X (features matrix) ###
# n = number of observations (rows) , p = Number of features (columns)
n, p = 50000, 1000
# ?np.random.randn
np.random.seed(0)
X = np.random.randn(n, p)
X

array([[ 1.76405235,  0.40015721,  0.97873798, ...,  0.0941923 ,
        -1.14761094, -0.35811408],
       [ 0.55596268,  0.89247389, -0.42231482, ...,  0.15843385,
        -1.14190142, -1.31097037],
       [-1.53292105, -1.71197016,  0.04613506, ..., -0.19240421,
        -1.21251574, -0.08059852],
       ...,
       [-0.33921446, -0.09624142,  0.57452305, ...,  1.4459948 ,
        -1.05949829, -0.63408931],
       [ 1.43637597, -1.01968609,  0.72719171, ...,  1.04694823,
        -0.28757397, -0.83730661],
       [-2.33502119, -1.47789717,  0.07842129, ..., -0.18023451,
        -2.84566402, -0.4275742 ]])

In [3]:
### 2-Create y (Target vector) ###
true_beta = np.random.randn(p)
y = X @ true_beta + np.random.randn(n)
y

array([-14.01580819,  -2.52796308,  -8.97422034, ..., -44.83955287,
       -40.10180972, -51.40607813])

## 3. Model estimation

In [4]:
### 1-Statsmodels OLS ###
# statsmodels.OLS → traditional econometrics flavor (gives summary with 𝑅2, 𝑝-values, etc.).
t0 = time.time()
X_const = sm.add_constant(X)   # add intercept
ols_model = sm.OLS(y, X_const).fit()
time_sm = time.time() - t0
time_sm

13.553045511245728

In [5]:
ols_model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results                            
==============================================================================
Dep. Variable:                      y   R-squared:                       0.999
Model:                            OLS   Adj. R-squared:                  0.999
Method:                 Least Squares   F-statistic:                 5.226e+04
Date:                Thu, 10 Sep 2026   Prob (F-statistic):               0.00
Time:                        14:54:46   Log-Likelihood:                -70527.
No. Observations:               50000   AIC:                         1.431e+05
Df Residuals:                   48999   BIC:                         1.519e+05
Df Model:                        1000                                         
Covariance Type:            nonrobust                                         
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const          0.0013      0.005      0.291      0.771      -0.008       0.010
x1            -0.4457      0.005    -98.138      0.000      -0.455      -0.437
x2            -0.6859      0.005   -151.589      0.000      -0.695      -0.677
x3             0.4435      0.005     98.557      0.000       0.435       0.452
x4             1.2348      0.004    275.946      0.000       1.226       1.244
x5            -0.6056      0.005   -133.312      0.000      -0.614      -0.597
x6             0.1497      0.005     33.171      0.000       0.141       0.158
x7             0.7942      0.005    175.767      0.000       0.785       0.803
x8             0.1048      0.005     23.190      0.000       0.096       0.114
x9            -1.1532      0.005   -253.125      0.000      -1.162      -1.144
x10            0.4678      0.005    103.732      0.000       0.459       0.477
x11            0.7195      0.005    159.077      0.000       0.711       0.728
x12           -0.8204      0.005   -180.737      0.000      -0.829      -0.812
x13           -1.5515      0.005   -344.138      0.000      -1.560      -1.543
x14            0.8979      0.005    197.949      0.000       0.889       0.907
x15            0.4353      0.005     95.814      0.000       0.426       0.444
x16            0.0039      0.005      0.855      0.393      -0.005       0.013
x17            1.5862      0.005    351.176      0.000       1.577       1.595
x18            0.0795      0.005     17.586      0.000       0.071       0.088
x19            1.0022      0.004    222.738      0.000       0.993       1.011
x20            0.3779      0.005     83.637      0.000       0.369       0.387
x21            1.5156      0.005    334.006      0.000       1.507       1.524
x22            0.4626      0.005    102.753      0.000       0.454       0.471
x23            1.3717      0.005    301.289      0.000       1.363       1.381
x24           -1.4373      0.005   -317.972      0.000      -1.446      -1.428
x25           -0.2611      0.005    -57.366      0.000      -0.270      -0.252
x26           -0.1499      0.005    -33.230      0.000      -0.159      -0.141
x27           -0.3372      0.005    -74.442      0.000      -0.346      -0.328
x28            2.9167      0.005    643.283      0.000       2.908       2.926
x29           -0.1831      0.005    -40.362      0.000      -0.192      -0.174
x30            1.2177      0.005    269.375      0.000       1.209       1.227
x31            0.0530      0.005     11.693      0.000       0.044       0.062
x32            1.1838      0.005    262.164      0.000       1.175       1.193
x33            1.1819      0.005    262.472      0.000       1.173       1.191
x34           -0.7521      0.005   -166.491      0.000      -0.761      -0.743
x35            1.2855      0.005    283.277      0.000       1.277       1.294
x3

In [6]:
# ols_model.params

In [7]:
### 2-Scikit-learn LinearRegression (OLS) ###
# sklearn.LinearRegression → ML flavor but still OLS solution, optimized for prediction.
t0 = time.time()
lr = LinearRegression(fit_intercept=True)
lr.fit(X, y)
time_sklearn_lr = time.time() - t0
time_sklearn_lr

4.232851982116699

In [8]:
# ?LinearRegression

In [9]:
lr.intercept_

np.float64(0.001316477401111224)

In [10]:
lr.coef_

array([-4.45689479e-01, -6.85906274e-01,  4.43518211e-01,  1.23475854e+00,
       -6.05575086e-01,  1.49656831e-01,  7.94230664e-01,  1.04818016e-01,
       -1.15320080e+00,  4.67823317e-01,  7.19466955e-01, -8.20440815e-01,
       -1.55153071e+00,  8.97923846e-01,  4.35260162e-01,  3.89231181e-03,
        1.58621060e+00,  7.94749906e-02,  1.00215974e+00,  3.77920164e-01,
        1.51559953e+00,  4.62576310e-01,  1.37168931e+00, -1.43729530e+00,
       -2.61069237e-01, -1.49862116e-01, -3.37240459e-01,  2.91673191e+00,
       -1.83068277e-01,  1.21765701e+00,  5.29541928e-02,  1.18380439e+00,
        1.18190353e+00, -7.52148626e-01,  1.28550107e+00, -2.12645344e+00,
        3.24009267e-01, -7.53464849e-01,  5.71316988e-01, -7.03657787e-01,
        5.17704465e-01,  2.01861778e-01, -9.48455534e-01,  1.28252955e+00,
       -4.36314689e-01,  1.10352453e+00, -1.50873157e+00, -6.86190804e-01,
       -8.00306166e-01,  1.27228104e+00, -9.57896542e-01,  7.36323058e-01,
        7.35044372e-01, -

In [11]:
lr.score(X,y)

0.9990632003715942

In [12]:
### 3-Scikit-learn SGDRegressor (Gradient Descent) ###
# sklearn.SGDRegressor → Stochastic gradient descent, useful for very large/high-dimensional data.
# Gradient Descent works best if features are on similar scales (without scaling, one feature with big values could dominate and slow convergence)

scaler = StandardScaler()                    #mean ≈ 0, variance ≈ 1
X_scaled = scaler.fit_transform(X)
t0 = time.time()
sgd = SGDRegressor(                          # Stochastic gradient descent (one sample per update) 
                   max_iter=1000,            # maximum number of passes over the training data
                   tol=1e-3,                 # stop early if loss improvement < tol
                   penalty=None,             # no regularization (pure linear regression)
                   eta0=0.1,                 # initial learning rate
                   learning_rate="constant", # learning rate stays fixed at eta0
                   random_state=0)           # reproducibility
sgd.fit(X_scaled, y)
time_sgd = time.time() - t0
time_sgd

1.095688819885254

In [13]:
# ?SGDRegressor

In [14]:
print(f"Statsmodels OLS time: {time_sm:.4f} sec")
print(f"Sklearn LinearRegression (OLS) time: {time_sklearn_lr:.4f} sec")
print(f"Sklearn SGDRegressor (Gradient Descent) time: {time_sgd:.4f} sec")

Statsmodels OLS time: 13.5530 sec
Sklearn LinearRegression (OLS) time: 4.2329 sec
Sklearn SGDRegressor (Gradient Descent) time: 1.0957 sec
